name: Deploy Notes
 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v1 
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v1 
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: run deploy.sh 
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        run: yarn install && yarn run docs:resource && yarn run docs:build